[INFO] [1740178781.309659428] [lamp_client]: Service trouvé, envoi des requêtes en boucle...
[INFO] [1740178781.310306032] [lamp_client]: Prochaine requête dans 9.58 secondes...
[INFO] [1740178790.912474862] [lamp_client]: Prochaine requête dans 3.70 secondes...
[INFO] [1740178794.679721349] [lamp_client]: Prochaine requête dans 5.88 secondes...
[INFO] [1740178800.567910487] [lamp_client]: Prochaine requête dans 3.85 secondes...
[INFO] [1740178804.430603757] [lamp_client]: Prochaine requête dans 2.22 secondes...
[INFO] [1740178806.702432196] [lamp_client]: Prochaine requête dans 9.29 secondes...
Traceback (most recent call last):
  File "/home/alan/ros2_ws/src/install/package_projet/lib/python3.10/site-packages/package_projet/client.py", line 44, in <module>
    main()
  File "/home/alan/ros2_ws/src/install/package_projet/lib/python3.10/site-packages/package_projet/client.py", line 41, in main
    rclpy.shutdown()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 130, in shutdown
    _shutdown(context=context)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/utilities.py", line 58, in shutdown
    return context.shutdown()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/context.py", line 102, in shutdown
    self.__context.shutdown()
rclpy._rclpy_pybind11.RCLError: failed to shutdown: rcl_shutdown already called on the given context, at ./src/rcl/init.c:241
